// ============================================================
//  SECURITY CAREER ROLES DATA
// ============================================================

const CAREER_ROLES = [
  {
    id: 'soc-analyst',
    title: 'SOC Analyst',
    subtitle: 'Security Operations Center',
    level: 'entry',
    track: 'defensive',
    icon: '&#128187;',
    color: '#58a6ff',
    salary: '$50,000 – $80,000',
    salaryMid: '$80,000 – $110,000',
    experience: '0–2 years',
    desc: 'Monitor security alerts around the clock, triage incidents, and escalate threats inside a Security Operations Center.',
    overview: 'SOC Analysts are the first line of defense. Working in shifts on SIEM dashboards and alert queues, they distinguish real threats from noise, investigate suspicious events, and escalate confirmed incidents to senior responders. Tier 1 analysts handle high-volume triage; Tier 2 analysts perform deeper investigation.',
    technicalSkills: [
      'SIEM platforms (Splunk, Microsoft Sentinel, IBM QRadar)',
      'Log analysis — Windows Event Logs, Syslog, firewall logs',
      'Network protocol fundamentals (TCP/IP, DNS, HTTP/S)',
      'Windows and Linux operating system basics',
      'Packet capture and analysis (Wireshark)',
      'Endpoint Detection & Response (EDR) tools',
      'Ticketing and documentation (ServiceNow, Jira)',
    ],
    softSkills: [
      'Attention to detail — finding signals in high-volume noise',
      'Written communication for incident documentation',
      'Calm and methodical under pressure',
      'Adaptability to shift work schedules',
      'Curiosity to investigate anomalies thoroughly',
    ],
    certifications: [
      { name: 'CompTIA Security+', desc: 'Industry-standard entry cert covering fundamentals. Often required by employers.', priority: 'essential' },
      { name: 'CompTIA CySA+', desc: 'Analyst-focused cert covering threat detection and behavioral analytics.', priority: 'recommended' },
      { name: 'BTL1 (Blue Team Labs)', desc: 'Hands-on defensive cert with practical SOC simulations. Highly respected.', priority: 'recommended' },
      { name: 'Google Cybersecurity Certificate', desc: 'Beginner-friendly online cert covering SOC fundamentals. Good for career changers.', priority: 'beginner' },
    ],
    entryPath: 'Most SOC analysts come from IT help desk or sysadmin backgrounds, or complete a cybersecurity boot camp. Strong candidates build hands-on skills via TryHackMe (Blue Team path), Blue Team Labs Online, or Security Blue Team courses before applying. Many SOC positions are open to candidates with Security+ and demonstrable lab experience.',
    careerPath: {
      from: ['IT Help Desk', 'Network Technician', 'Boot Camp Graduate'],
      to: ['SOC Tier 2 / Tier 3', 'Incident Responder', 'Threat Intelligence Analyst', 'Security Engineer'],
    },
    dayInLife: 'Start shift by reviewing overnight alerts. Work through the alert queue in SIEM — investigate flagged logins, malware detections, and network anomalies. Write tickets for confirmed incidents. Escalate anything requiring deeper investigation. Tune alert rules to reduce false positives. Brief incoming shift on open cases.',
    resources: ['TryHackMe — SOC Level 1 path', 'Blue Team Labs Online', 'LetsDefend platform', 'Security Blue Team courses'],
  },
  {
    id: 'pentest-junior',
    title: 'Penetration Tester',
    subtitle: 'Ethical Hacker / Offensive Security',
    level: 'mid',
    track: 'offensive',
    icon: '&#127993;',
    color: '#f85149',
    salary: '$75,000 – $110,000',
    salaryMid: '$110,000 – $160,000',
    experience: '1–3 years',
    desc: 'Conduct authorized attacks against networks, systems, and applications to find vulnerabilities before malicious hackers do.',
    overview: 'Penetration testers simulate real-world attacks to evaluate an organization\'s defenses. They perform structured assessments of networks, web applications, and infrastructure, then write detailed reports documenting findings and remediation guidance. The role requires both technical attack skills and clear communication.',
    technicalSkills: [
      'Kali Linux and offensive security tooling',
      'Network scanning and enumeration (Nmap, Netcat)',
      'Web application testing (Burp Suite, OWASP Top 10)',
      'Exploitation frameworks (Metasploit)',
      'Scripting and automation (Python, Bash)',
      'Active Directory attack techniques',
      'Technical report writing',
      'Post-exploitation and privilege escalation',
    ],
    softSkills: [
      'Creative adversarial thinking — how would an attacker approach this?',
      'Clear written communication for technical and executive reports',
      'Ethics and strict scope adherence',
      'Persistence through complex, multi-step challenges',
      'Explaining technical risk to non-technical stakeholders',
    ],
    certifications: [
      { name: 'OSCP (Offensive Security)', desc: 'The gold standard pentest cert — 24-hour hands-on exam. Required by most employers.', priority: 'essential' },
      { name: 'eJPT (eLearnSecurity)', desc: 'Entry-level practical pentest cert. Good first step before OSCP.', priority: 'beginner' },
      { name: 'PNPT (TCM Security)', desc: 'Practical Network Penetration Tester — affordable, hands-on, highly regarded.', priority: 'recommended' },
      { name: 'CompTIA PenTest+', desc: 'Vendor-neutral pentest cert. Less hands-on than OSCP but useful for job listings.', priority: 'recommended' },
    ],
    entryPath: 'Build skills through HackTheBox, TryHackMe (Offensive path), and CTF competitions. Complete TCM Security or INE courses. Earn eJPT or PNPT first, then pursue OSCP. Bug bounty hunting builds real-world experience. Junior pentest roles often accept candidates with strong lab portfolios and one practical cert.',
    careerPath: {
      from: ['SOC Analyst', 'IT/Network Admin', 'CTF competitor', 'Self-taught via HTB/THM'],
      to: ['Senior Penetration Tester', 'Red Team Operator', 'AppSec Engineer', 'Security Consultant'],
    },
    dayInLife: 'Review scope and rules of engagement for an assessment. Run enumeration scans against target network. Identify and exploit vulnerabilities in web apps and services. Document each finding with evidence, CVSS score, and remediation steps. Write final report. Present findings to the client\'s security team.',
    resources: ['HackTheBox (HTB Academy)', 'TryHackMe — Offensive path', 'TCM Security courses', 'PortSwigger Web Security Academy (free)'],
  },
  {
    id: 'incident-responder',
    title: 'Incident Responder',
    subtitle: 'DFIR / Cyber Incident Response',
    level: 'mid',
    track: 'defensive',
    icon: '&#128680;',
    color: '#d29922',
    salary: '$85,000 – $130,000',
    salaryMid: '$130,000 – $180,000',
    experience: '2–5 years',
    desc: 'Lead the investigation, containment, and recovery from active security breaches and cyberattacks.',
    overview: 'Incident Responders are called in when an organization is actively under attack or has been compromised. They conduct forensic investigations, contain the spread of the attack, eradicate the threat, and restore normal operations. The role often involves high-pressure situations, executive communication, and deep technical investigation.',
    technicalSkills: [
      'Digital forensics (FTK, Autopsy, X-Ways)',
      'Memory forensics (Volatility framework)',
      'Endpoint Detection & Response (CrowdStrike, SentinelOne)',
      'Log analysis at scale (Splunk, ELK)',
      'Malware triage and sandbox analysis',
      'Network forensics (Wireshark, Zeek, Suricata)',
      'Timeline construction and evidence correlation',
      'Chain of custody and legal considerations',
    ],
    softSkills: [
      'Composure and decisive decision-making under pressure',
      'Executive communication — briefing C-suite during a crisis',
      'Meticulous documentation throughout the investigation',
      'Ability to manage multiple workstreams simultaneously',
      'Empathy for affected users during stressful incidents',
    ],
    certifications: [
      { name: 'GCIH (GIAC Certified Incident Handler)', desc: 'SANS-backed cert covering the full IR lifecycle. Industry benchmark.', priority: 'essential' },
      { name: 'GCFA (GIAC Certified Forensic Analyst)', desc: 'Advanced forensic analysis — disk, memory, and network.', priority: 'recommended' },
      { name: 'BTL2 (Blue Team Labs Level 2)', desc: 'Hands-on IR and forensics certification. Practical and respected.', priority: 'recommended' },
      { name: 'GCFE (GIAC Certified Forensic Examiner)', desc: 'Windows forensics focused. Good for digital evidence investigation.', priority: 'recommended' },
    ],
    entryPath: 'Most incident responders come from SOC analyst backgrounds where they developed triage skills. Supplement with digital forensics training (SANS FOR508 or similar), practice with Volatility and Autopsy, and build a home lab for malware analysis. Some enter from law enforcement or military cyber units.',
    careerPath: {
      from: ['SOC Analyst (Tier 2/3)', 'Digital Forensics Analyst', 'Security Engineer'],
      to: ['IR Team Lead', 'Threat Hunter', 'DFIR Manager', 'Security Architect'],
    },
    dayInLife: 'Receive alert about potential ransomware infection. Immediately isolate affected hosts, collect forensic images, and begin timeline analysis. Identify the initial entry vector from log data. Contain spread across the network. Brief the CISO on scope and impact. Coordinate with IT on recovery. Write post-incident report with root cause and recommendations.',
    resources: ['SANS FOR508 course', 'Cyber Defenders — forensics labs', 'Blue Team Labs Online', 'Volatility 3 documentation'],
  },
  {
    id: 'security-engineer',
    title: 'Security Engineer',
    subtitle: 'Security Infrastructure & Operations',
    level: 'mid',
    track: 'engineering',
    icon: '&#9881;',
    color: '#3fb950',
    salary: '$100,000 – $145,000',
    salaryMid: '$145,000 – $200,000',
    experience: '3–6 years',
    desc: 'Design, build, and maintain the security tools, controls, and infrastructure that protect the organization.',
    overview: 'Security Engineers are the builders of the security team. They implement and maintain SIEM platforms, firewalls, EDR tools, IAM systems, and security automation. Unlike analysts who respond to events, engineers focus on building systems that detect and prevent threats at scale. The role bridges IT infrastructure and security.',
    technicalSkills: [
      'Firewall, IDS/IPS, and proxy configuration',
      'SIEM deployment and tuning (Splunk, Sentinel)',
      'Identity and Access Management (IAM/PAM)',
      'Scripting and automation (Python, PowerShell, Terraform)',
      'Cloud security (AWS/Azure/GCP security services)',
      'PKI and certificate management',
      'Vulnerability management programs',
      'Security tool integration and API usage',
    ],
    softSkills: [
      'Systems thinking — understanding how components interact',
      'Collaboration with IT, DevOps, and development teams',
      'Project management for multi-month deployments',
      'Translating security requirements into technical designs',
      'Documentation for complex systems',
    ],
    certifications: [
      { name: 'CISSP (ISC²)', desc: 'The premier security management cert covering all 8 security domains. Often required for senior roles.', priority: 'essential' },
      { name: 'AWS Security Specialty', desc: 'Validates AWS security architecture and implementation skills.', priority: 'recommended' },
      { name: 'GCIA (GIAC Certified Intrusion Analyst)', desc: 'Deep network security monitoring and analysis skills.', priority: 'recommended' },
      { name: 'CCSP (Certified Cloud Security Professional)', desc: 'Cloud security architecture covering multiple platforms.', priority: 'recommended' },
    ],
    entryPath: 'Security Engineers typically come from network engineering, systems administration, or SOC backgrounds. Gain experience managing security tools as a sysadmin, then move into a dedicated security engineering role. Cloud certification alongside security certs accelerates this path significantly.',
    careerPath: {
      from: ['Network/Systems Administrator', 'SOC Analyst (Senior)', 'IT Engineer'],
      to: ['Senior Security Engineer', 'Cloud Security Architect', 'Security Architect', 'Engineering Manager'],
    },
    dayInLife: 'Morning: review deployment of new SIEM detection rules. Meeting with DevOps team to discuss secrets management integration. Afternoon: tune EDR policies causing false positives in production. Script automation for certificate rotation. Write design document for new identity governance rollout.',
    resources: ['SANS SEC401 / SEC501', 'Cloud security labs (AWS, Azure, GCP free tiers)', 'TryHackMe — Security Engineer path', 'CISSP study guides (Sybex)'],
  },
  {
    id: 'appsec-engineer',
    title: 'AppSec Engineer',
    subtitle: 'Application Security',
    level: 'mid',
    track: 'engineering',
    icon: '&#128187;',
    color: '#bc8cff',
    salary: '$110,000 – $155,000',
    salaryMid: '$155,000 – $220,000',
    experience: '3–6 years',
    desc: 'Secure software from design through deployment — code review, threat modeling, SAST/DAST tooling, and developer training.',
    overview: 'Application Security Engineers work at the intersection of software development and security. They review code for vulnerabilities, design secure software architectures, integrate automated security testing into CI/CD pipelines, and train developers to write more secure code. The goal is to shift security left — finding issues at design time rather than in production.',
    technicalSkills: [
      'Secure code review (Python, JavaScript, Java, Go)',
      'OWASP Top 10 and web vulnerability classes',
      'SAST tools (Semgrep, SonarQube, Checkmarx)',
      'DAST tools (Burp Suite, OWASP ZAP)',
      'Threat modeling (STRIDE, PASTA)',
      'CI/CD pipeline security (GitHub Actions, Jenkins)',
      'API security testing',
      'Dependency vulnerability management (Dependabot, Snyk)',
    ],
    softSkills: [
      'Developer empathy — security guidance that developers will actually follow',
      'Patient communication to non-security engineers',
      'Ability to explain risk in business terms',
      'Balancing security ideals with shipping velocity',
      'Building security culture, not just enforcing rules',
    ],
    certifications: [
      { name: 'GWEB (GIAC Web Application Penetration Tester)', desc: 'Web app security testing and exploitation. Strong for AppSec roles.', priority: 'essential' },
      { name: 'CSSLP (ISC² Certified Secure Software Lifecycle)', desc: 'Covers secure SDLC principles comprehensively.', priority: 'recommended' },
      { name: 'OSWE (Offensive Security Web Expert)', desc: 'Advanced web app exploitation. Highly respected by technical teams.', priority: 'advanced' },
      { name: 'BSCP (PortSwigger Burp Suite Certified)', desc: 'Practical web security cert from the makers of Burp Suite.', priority: 'recommended' },
    ],
    entryPath: 'Most AppSec engineers come from software development backgrounds who discovered security interest, or from penetration testing with web app focus. Complete PortSwigger Web Security Academy (free and excellent), practice with vulnerable-by-design apps (DVWA, Juice Shop), and build experience reviewing real codebases.',
    careerPath: {
      from: ['Software Developer', 'Web Application Pentester', 'Security Engineer'],
      to: ['Principal AppSec Engineer', 'Security Architect', 'AppSec Manager', 'CISO'],
    },
    dayInLife: 'Review a pull request for security issues in authentication logic. Threat model a new microservice with the product team. Update SAST pipeline rules to catch a newly discovered vulnerability pattern. Conduct 1:1 training session with a developer on SQL injection prevention. Write finding report for last week\'s code review.',
    resources: ['PortSwigger Web Security Academy (free)', 'OWASP Testing Guide', 'Semgrep rules documentation', 'Secure Code Warrior platform'],
  },
  {
    id: 'cloud-security',
    title: 'Cloud Security Engineer',
    subtitle: 'Cloud Infrastructure Security',
    level: 'mid',
    track: 'engineering',
    icon: '&#9729;',
    color: '#06b6d4',
    salary: '$120,000 – $165,000',
    salaryMid: '$165,000 – $230,000',
    experience: '3–6 years',
    desc: 'Secure cloud infrastructure across AWS, Azure, and GCP — IAM design, misconfiguration detection, runtime protection, and compliance.',
    overview: 'Cloud Security Engineers specialize in securing public cloud environments. As organizations migrate infrastructure to AWS, Azure, and GCP, the attack surface shifts dramatically. This role focuses on identity and access management policy design, detecting misconfigurations, container and Kubernetes security, data protection, and building automated guardrails using infrastructure-as-code.',
    technicalSkills: [
      'AWS, Azure, and/or GCP security services',
      'Cloud Security Posture Management (CSPM — Wiz, Prisma, Defender)',
      'IAM policy design and least-privilege enforcement',
      'Infrastructure-as-Code security (Terraform, CloudFormation)',
      'Container and Kubernetes security',
      'Cloud networking (VPCs, security groups, private endpoints)',
      'Secrets management (Vault, AWS Secrets Manager)',
      'Cloud compliance frameworks (CIS Benchmarks, NIST)',
    ],
    softSkills: [
      'DevOps collaboration — security as an enabler, not a blocker',
      'Continuous learning — cloud evolves at extreme pace',
      'Infrastructure thinking — understanding dependencies at scale',
      'Communicating risk to engineering managers and architects',
    ],
    certifications: [
      { name: 'AWS Certified Security – Specialty', desc: 'The most recognized cloud security cert for AWS environments.', priority: 'essential' },
      { name: 'AZ-500 (Microsoft Azure Security)', desc: 'Azure-focused security cert covering Defender, Sentinel, and IAM.', priority: 'essential' },
      { name: 'CCSP (Certified Cloud Security Professional)', desc: 'Vendor-neutral cloud security architecture cert. Strong for senior roles.', priority: 'recommended' },
      { name: 'CCSK (Certificate of Cloud Security Knowledge)', desc: 'Foundational cloud security cert from CSA. Good starting point.', priority: 'beginner' },
    ],
    entryPath: 'Cloud security roles are accessible to cloud engineers (DevOps/SRE) who develop security knowledge, or security engineers who gain cloud expertise. Start with AWS/Azure free tier labs, earn a cloud platform cert (Solutions Architect), then layer the security specialty cert on top.',
    careerPath: {
      from: ['Cloud Engineer / DevOps', 'Security Engineer', 'Systems Administrator'],
      to: ['Cloud Security Architect', 'Principal Security Engineer', 'CISO', 'VP of Infrastructure Security'],
    },
    dayInLife: 'Review CSPM findings for new critical misconfigurations. Write Terraform policy-as-code rules to prevent public S3 buckets from being created. Meeting with the data team about encrypting a new data pipeline. Investigate an anomalous IAM role assumption from an EC2 instance. Update AWS Security Hub compliance dashboard.',
    resources: ['A Cloud Guru / CloudAcademy', 'AWS Security workshops (free)', 'Wiz.io free training', 'Cloud Security Alliance resources'],
  },
  {
    id: 'threat-intel',
    title: 'Threat Intelligence Analyst',
    subtitle: 'Cyber Threat Intelligence (CTI)',
    level: 'mid',
    track: 'defensive',
    icon: '&#128269;',
    color: '#ffa657',
    salary: '$75,000 – $115,000',
    salaryMid: '$115,000 – $160,000',
    experience: '2–5 years',
    desc: 'Research threat actors, tactics, and indicators to produce intelligence that helps defenders anticipate and counter attacks.',
    overview: 'Threat Intelligence Analysts bridge the gap between raw security data and actionable decisions. They monitor threat actor groups, analyze malware campaigns, track indicators of compromise, and produce intelligence reports that help SOC teams, security engineers, and executives understand the threat landscape facing their organization.',
    technicalSkills: [
      'MITRE ATT&CK framework (TTPs mapping)',
      'OSINT techniques and tools',
      'Dark web and underground forum monitoring',
      'IOC analysis and threat intel platforms (MISP, ThreatConnect, OpenCTI)',
      'Basic malware analysis (static and dynamic)',
      'Python scripting for automation and data processing',
      'Threat intel report writing (strategic, operational, tactical)',
      'Diamond Model and kill chain frameworks',
    ],
    softSkills: [
      'Analytical research skills — synthesizing large volumes of information',
      'Clear written communication at multiple classification levels',
      'Geopolitical and cultural awareness',
      'Intellectual curiosity to follow complex investigation threads',
      'Objectivity — avoiding confirmation bias in analysis',
    ],
    certifications: [
      { name: 'GCTI (GIAC Cyber Threat Intelligence)', desc: 'Comprehensive threat intelligence methodology cert from SANS.', priority: 'essential' },
      { name: 'CTIA (EC-Council)', desc: 'Certified Threat Intelligence Analyst covering frameworks and methodologies.', priority: 'recommended' },
      { name: 'Recorded Future Intelligence Fundamentals', desc: 'Platform-specific cert that also covers core CTI concepts.', priority: 'recommended' },
    ],
    entryPath: 'Many CTI analysts come from SOC backgrounds where they developed anomaly investigation skills, or from military/government intelligence backgrounds. Journalism, political science, and research backgrounds are surprisingly common due to the analytical writing demands. Start by consuming threat intel reports from Mandiant, CrowdStrike, and Microsoft MSTIC.',
    careerPath: {
      from: ['SOC Analyst', 'Military/Government Intelligence', 'Research/Journalism background'],
      to: ['Senior CTI Analyst', 'Threat Hunter', 'CTI Program Manager', 'Security Researcher'],
    },
    dayInLife: 'Morning: review overnight threat feeds for new IOCs affecting your industry sector. Update threat actor profile for a ransomware group with new TTPs. Write a tactical intelligence brief for the SOC team about a new phishing campaign. Afternoon: briefing with the CISO on emerging threats for Q2. Contribute IOCs to community sharing platforms.',
    resources: ['SANS FOR578 (CTI course)', 'Mandiant / CrowdStrike public threat reports', 'MITRE ATT&CK Navigator', 'MISP community platform'],
  },
  {
    id: 'dfir',
    title: 'Digital Forensics Analyst',
    subtitle: 'DFIR / Forensic Investigations',
    level: 'mid',
    track: 'defensive',
    icon: '&#128300;',
    color: '#e879f9',
    salary: '$70,000 – $105,000',
    salaryMid: '$105,000 – $150,000',
    experience: '2–5 years',
    desc: 'Collect, preserve, and analyze digital evidence from computers, mobile devices, and networks for incident response or legal proceedings.',
    overview: 'Digital Forensics Analysts investigate what happened after a security incident or crime. Working with strict evidence handling procedures, they extract data from storage media, recover deleted files, analyze memory, and reconstruct timelines of events. Findings may be used in legal proceedings, requiring testimony-ready documentation.',
    technicalSkills: [
      'Disk forensics (FTK, Autopsy, X-Ways Forensics)',
      'Memory forensics (Volatility 3)',
      'Mobile device forensics (Cellebrite UFED)',
      'Network forensics (Wireshark, NetworkMiner)',
      'Windows artifact analysis (Registry, prefetch, LNK files)',
      'Linux forensics (/proc, journal logs, bash history)',
      'Write blockers and forensically sound acquisition',
      'Chain of custody documentation',
    ],
    softSkills: [
      'Meticulous, methodical documentation',
      'Understanding of legal and evidentiary standards',
      'Objectivity — the evidence determines conclusions, not vice versa',
      'Ability to testify and explain technical findings to non-technical audiences',
      'Patience with time-consuming analysis processes',
    ],
    certifications: [
      { name: 'GCFE (GIAC Certified Forensic Examiner)', desc: 'Windows forensics focused. Covers core artifacts and investigation methodology.', priority: 'essential' },
      { name: 'GCFA (GIAC Certified Forensic Analyst)', desc: 'Advanced forensics covering memory, timeline analysis, and threat hunting.', priority: 'recommended' },
      { name: 'EnCE (EnCase Certified Examiner)', desc: 'Widely recognized in law enforcement and corporate forensics.', priority: 'recommended' },
      { name: 'Cellebrite CCO', desc: 'Mobile device forensics certification. Essential for mobile-focused roles.', priority: 'recommended' },
    ],
    entryPath: 'Many enter from IT or law enforcement backgrounds. Complete SANS FOR500 or equivalent, practice with Autopsy on sample disk images (available from digital forensics competitions like DFIR.training), and build a home lab with virtual machines representing incident scenarios.',
    careerPath: {
      from: ['SOC Analyst', 'IT/Systems Admin', 'Law Enforcement'],
      to: ['IR Team Lead', 'DFIR Consultant', 'Forensics Manager', 'Law Enforcement Cyber Unit'],
    },
    dayInLife: 'Receive a disk image from a compromised workstation. Create forensic copy, verify hash. Begin artifact analysis: review browser history, recently accessed files, Registry run keys, event logs. Build a timeline of attacker activity. Identify the initial compromise vector. Write a forensic report suitable for legal review if needed.',
    resources: ['SANS FOR500 / FOR508 courses', 'DFIR.training practice images', 'Cyber Defenders forensics labs', 'Autopsy documentation'],
  },
  {
    id: 'red-team',
    title: 'Red Team Operator',
    subtitle: 'Advanced Adversary Simulation',
    level: 'senior',
    track: 'offensive',
    icon: '&#127919;',
    color: '#f87171',
    salary: '$120,000 – $170,000',
    salaryMid: '$170,000 – $250,000',
    experience: '5–8 years',
    desc: 'Simulate advanced persistent threats through multi-phase attack campaigns to test an organization\'s detection and response capabilities.',
    overview: 'Red Team Operators go beyond standard penetration testing. They run realistic, long-duration adversary simulations — mimicking nation-state and ransomware group TTPs — to test whether the blue team can detect and respond. Operations include initial access, persistence, lateral movement, and objective completion, all while actively evading detection.',
    technicalSkills: [
      'Advanced exploitation and post-exploitation techniques',
      'C2 frameworks (Cobalt Strike, Havoc, Sliver)',
      'Custom implant and payload development',
      'Active Directory attack chains (Kerberoasting, DCSync, Golden Ticket)',
      'EDR and AV evasion techniques',
      'Physical security testing and lock picking',
      'Social engineering and pretexting',
      'OPSEC (operational security) during engagements',
    ],
    softSkills: [
      'Creative adversarial thinking — approaching defense from the attacker\'s perspective',
      'Patience for long-duration operations with careful, deliberate movement',
      'Precise technical report writing at executive and technical levels',
      'Strict ethical boundaries and scope adherence',
      'Collaboration with blue team for purple team exercises',
    ],
    certifications: [
      { name: 'OSCP (Offensive Security)', desc: 'Prerequisite for most red team roles. Demonstrates exploitation fundamentals.', priority: 'essential' },
      { name: 'CRTO (Red Team Ops — Zero-Point Security)', desc: 'Cobalt Strike and red team TTPs. Highly practical and respected.', priority: 'essential' },
      { name: 'CRTE (Certified Red Team Expert)', desc: 'Advanced Active Directory red team operations.', priority: 'recommended' },
      { name: 'OSEP (Offensive Security Experienced Penetration Tester)', desc: 'Advanced evasion, AD attacks, and complex environments.', priority: 'advanced' },
    ],
    entryPath: 'Red team roles require 3–5 years of penetration testing experience minimum. Earn OSCP first, then pursue CRTO and active directory-specific training. Contribute to open-source offensive tools, participate in CTF teams, and build demonstrable malware development skills. Most operators come from senior pentest positions.',
    careerPath: {
      from: ['Senior Penetration Tester', 'Security Researcher', 'Exploit Developer'],
      to: ['Red Team Lead', 'Offensive Security Manager', 'Security Consultant', 'Security Researcher'],
    },
    dayInLife: 'Day 3 of a 2-week red team engagement. Use previously phished credentials to access VPN. Enumerate Active Directory without triggering SIEM alerts. Identify over-privileged service account. Perform Kerberoasting offline. Crack hash and escalate to domain admin equivalent. Document TTPs used. Ensure blue team detection coverage will be tested.',
    resources: ['Zero-Point Security CRTO course', 'HackTheBox ProLabs (RastaLabs, Offshore)', 'SpecterOps training', 'Cobalt Strike documentation'],
  },
  {
    id: 'security-architect',
    title: 'Security Architect',
    subtitle: 'Enterprise Security Architecture',
    level: 'senior',
    track: 'engineering',
    icon: '&#127959;',
    color: '#34d399',
    salary: '$145,000 – $190,000',
    salaryMid: '$190,000 – $270,000',
    experience: '8–12 years',
    desc: 'Design enterprise-wide security frameworks, reference architectures, and controls that align security strategy with business objectives.',
    overview: 'Security Architects operate at the intersection of business, technology, and risk. They design security reference architectures, define standards and patterns for the engineering teams to follow, lead security reviews for major projects, and advise leadership on strategic security investments. The role requires both broad technical depth and executive communication skills.',
    technicalSkills: [
      'Enterprise architecture frameworks (TOGAF, SABSA, Zachman)',
      'Zero Trust architecture design principles',
      'Network security architecture (segmentation, DMZ design)',
      'Cloud security architecture across multiple platforms',
      'Identity architecture (IAM, federation, zero trust identity)',
      'Cryptography and PKI design',
      'Risk frameworks (NIST CSF, ISO 27001, COBIT)',
      'Security reference architecture documentation',
    ],
    softSkills: [
      'Executive communication — presenting risk and recommendations to C-suite',
      'Strategic thinking and long-term planning',
      'Business acumen — understanding how security enables or constrains business',
      'Stakeholder management across security, IT, and business units',
      'Ability to make decisions under uncertainty and incomplete information',
    ],
    certifications: [
      { name: 'CISSP (ISC²)', desc: 'Required for virtually all security architect positions. Covers all 8 security domains.', priority: 'essential' },
      { name: 'CCSP (ISC²)', desc: 'Cloud security architecture. Increasingly important as workloads shift to cloud.', priority: 'essential' },
      { name: 'CISM (ISACA)', desc: 'Security management and governance focus. Valued in enterprise and consulting.', priority: 'recommended' },
      { name: 'SABSA Chartered Security Architect', desc: 'Enterprise security architecture methodology. Most rigorous architecture cert.', priority: 'advanced' },
    ],
    entryPath: 'Security Architects are built over 8–12 years of progressive security experience across multiple domains. Depth in one area (e.g., network security or IAM) combined with breadth across all domains is the typical path. Move through security engineering roles, then into senior technical lead or principal engineer positions before architect.',
    careerPath: {
      from: ['Senior Security Engineer', 'Cloud Security Engineer', 'Senior IR / Pentest Lead'],
      to: ['CISO', 'VP of Security', 'Principal Architect', 'Security Consultant (Independent)'],
    },
    dayInLife: 'Morning: review security design document for new data lake architecture — provide comments on encryption, access controls, and logging. Meeting with CTO to discuss zero trust roadmap priorities. Afternoon: present quarterly security architecture review to the board. Final hour: review a proposed cloud migration design for a business-critical application.',
    resources: ['CISSP Official Study Guide (Sybex)', 'NIST Cybersecurity Framework documentation', 'SANS Leadership courses', 'SABSA Institute resources'],
  },
  {
    id: 'grc-analyst',
    title: 'GRC Analyst',
    subtitle: 'Governance, Risk & Compliance',
    level: 'entry',
    track: 'governance',
    icon: '&#128203;',
    color: '#94a3b8',
    salary: '$55,000 – $85,000',
    salaryMid: '$85,000 – $130,000',
    experience: '0–3 years',
    desc: 'Manage security governance frameworks, risk assessments, compliance programs, and policy to ensure organizational accountability.',
    overview: 'GRC Analysts are the bridge between security controls and regulatory requirements. They manage compliance programs for standards like SOC 2, ISO 27001, HIPAA, and PCI DSS; conduct risk assessments; write and maintain security policies; and coordinate audits. While less technical than other roles, strong GRC professionals have significant organizational impact.',
    technicalSkills: [
      'Risk frameworks (NIST CSF, NIST 800-53, ISO 27001)',
      'Compliance standards (SOC 2, PCI DSS, HIPAA, GDPR)',
      'GRC platforms (ServiceNow GRC, RSA Archer, OneTrust)',
      'Risk assessment methodology',
      'Policy and procedure writing',
      'Audit management and evidence collection',
      'Third-party vendor risk assessment',
      'Basic understanding of technical security controls',
    ],
    softSkills: [
      'Excellent written communication for policies and reports',
      'Auditing mindset — attention to detail and process',
      'Stakeholder management across all organizational levels',
      'Project management for compliance programs',
      'Regulatory interpretation and practical application',
    ],
    certifications: [
      { name: 'CompTIA Security+', desc: 'Foundational technical knowledge that supports GRC work.', priority: 'essential' },
      { name: 'CISA (ISACA Certified Information Systems Auditor)', desc: 'The premier audit and assurance certification. Highly valued in GRC.', priority: 'essential' },
      { name: 'CISM (ISACA)', desc: 'Security management certification. Strong for senior GRC roles.', priority: 'recommended' },
      { name: 'CRISC (Certified in Risk and Information Systems Control)', desc: 'Risk-focused cert. Valuable for risk management specialization.', priority: 'recommended' },
    ],
    entryPath: 'GRC is one of the most accessible entry points into cybersecurity for people from non-technical backgrounds. Finance, audit, legal, and business backgrounds transition well. Earn Security+ for technical credibility, study NIST CSF and ISO 27001, and target junior GRC analyst or compliance analyst positions.',
    careerPath: {
      from: ['Auditor / Finance', 'Legal / Compliance background', 'IT Helpdesk', 'Recent graduate (business or IT)'],
      to: ['GRC Manager', 'Compliance Director', 'Risk Manager', 'CISO', 'vCISO Consultant'],
    },
    dayInLife: 'Morning: update SOC 2 evidence repository with new access review documentation. Meeting with engineering to discuss control gaps identified in last week\'s audit. Afternoon: review third-party vendor security questionnaire for a new SaaS provider. Write new acceptable use policy based on last quarter\'s policy gap analysis.',
    resources: ['NIST Cybersecurity Framework (free)', 'ISACA study materials', 'SANS MGT512 Security Leadership', 'ISO 27001 standard documentation'],
  },
  {
    id: 'malware-analyst',
    title: 'Malware Analyst',
    subtitle: 'Reverse Engineering & Malware Research',
    level: 'senior',
    track: 'defensive',
    icon: '&#128027;',
    color: '#fb923c',
    salary: '$100,000 – $145,000',
    salaryMid: '$145,000 – $210,000',
    experience: '4–8 years',
    desc: 'Analyze malicious code to understand how it works, identify capabilities, extract indicators of compromise, and develop detections.',
    overview: 'Malware Analysts dissect malicious software to understand attacker techniques. Through both dynamic analysis (running malware in controlled sandboxes) and static analysis (reading disassembled code), they reverse engineer malware families, document capabilities, and extract IOCs for defenders. Advanced analysts work on nation-state APT implants and novel evasion techniques.',
    technicalSkills: [
      'x86/x64 assembly language reading',
      'Disassemblers and decompilers (IDA Pro, Ghidra, Binary Ninja)',
      'Dynamic analysis debuggers (x64dbg, OllyDbg, WinDbg)',
      'Sandbox analysis (Any.run, Cuckoo, Joe Sandbox)',
      'Windows internals (PE format, API calls, process injection)',
      'Anti-analysis detection and bypass techniques',
      'Python scripting for automation and YARA rule writing',
      'Network traffic analysis for C2 identification',
    ],
    softSkills: [
      'Extreme patience — malware analysis can take days per sample',
      'Curiosity and persistence when facing obfuscation',
      'Precise technical documentation and IOC reporting',
      'Ability to work independently on complex, ambiguous problems',
      'Staying current on rapidly evolving threat actor techniques',
    ],
    certifications: [
      { name: 'GREM (GIAC Reverse Engineering Malware)', desc: 'The gold standard malware analysis cert. Covers static and dynamic analysis.', priority: 'essential' },
      { name: 'GCFA (GIAC Certified Forensic Analyst)', desc: 'Forensic analysis skills that complement malware investigation.', priority: 'recommended' },
    ],
    entryPath: 'Malware analysis is among the most technically demanding specializations. Build strong programming foundations (C, Python), learn x86 assembly, and practice with Ghidra on crackme challenges. Complete malware analysis courses (SANS FOR610 or Practical Malware Analysis book). Participate in malware analysis CTF challenges.',
    careerPath: {
      from: ['Incident Responder', 'Security Researcher', 'Programmer with security interest'],
      to: ['Senior Malware Researcher', 'AV/EDR Research Engineer', 'APT Researcher', 'Threat Intelligence Lead'],
    },
    dayInLife: 'Receive a suspicious binary flagged by EDR. Static analysis: examine PE headers, strings, imports — spot anti-debugging checks. Dynamic analysis: run in isolated VM, monitor API calls, network connections, and registry changes. Identify the malware family: Cobalt Strike beacon. Extract C2 configuration. Write YARA detection rule. Publish IOCs to threat intel platform.',
    resources: ['Practical Malware Analysis (book by Sikorski & Honig)', 'SANS FOR610 course', 'any.run and hybrid-analysis.com', 'Ghidra (free NSA tool)'],
  },
  {
    id: 'ciso',
    title: 'CISO',
    subtitle: 'Chief Information Security Officer',
    level: 'executive',
    track: 'governance',
    icon: '&#129346;',
    color: '#c084fc',
    salary: '$180,000 – $300,000',
    salaryMid: '$300,000 – $500,000+',
    experience: '15+ years',
    desc: 'Executive responsible for the entire information security program — strategy, risk management, team leadership, and board-level communication.',
    overview: 'The CISO is the senior executive accountable for an organization\'s cybersecurity posture. They own the security strategy, define risk tolerance in consultation with the board, manage the security budget and team, communicate threats to executives and directors, and make high-stakes decisions during major incidents. The role is as much about leadership and business acumen as technical expertise.',
    technicalSkills: [
      'Broad knowledge across all security domains (not necessarily deep in all)',
      'Risk quantification frameworks (FAIR methodology)',
      'Security metrics, KPIs, and board reporting',
      'Budget management and vendor contract negotiation',
      'Regulatory and legal landscape (GDPR, HIPAA, SEC requirements)',
      'Security program maturity models (CMMC, NIST CSF)',
      'Crisis management and incident command',
      'Strategic technology roadmap development',
    ],
    softSkills: [
      'Executive presence and board communication skills',
      'Translating technical risk into business impact language',
      'Team building and leadership across diverse technical disciplines',
      'Crisis communication — public, regulatory, and internal',
      'Strategic thinking and multi-year planning',
      'Negotiation with vendors, auditors, and regulators',
    ],
    certifications: [
      { name: 'CISSP (ISC²)', desc: 'Near-universal requirement. Demonstrates broad security domain knowledge.', priority: 'essential' },
      { name: 'CISM (ISACA)', desc: 'Management-focused cert. Highly aligned with CISO responsibilities.', priority: 'essential' },
      { name: 'MBA or MS in Cybersecurity', desc: 'Advanced degrees common at enterprise CISO level, especially for board communication credibility.', priority: 'recommended' },
      { name: 'CRISC (ISACA)', desc: 'Risk management cert. Valuable for organizations where risk management is a primary CISO function.', priority: 'recommended' },
    ],
    entryPath: 'There is no shortcut to CISO. The typical path spans 15+ years: technical roles → team lead → manager → director → VP → CISO. Many come from security engineering, IR, or architecture backgrounds. Building business acumen alongside technical skills throughout your career is essential. Consider Deputy CISO or VP/Director of Security as intermediate steps.',
    careerPath: {
      from: ['VP / Director of Security', 'Security Architect', 'Security Engineering Manager'],
      to: ['CTO', 'Board Advisor', 'Independent CISO Consultant', 'Startup Founder'],
    },
    dayInLife: 'Board presentation on Q1 security posture and emerging ransomware threat landscape. 1:1 with IR team lead on ongoing incident. Budget review with CFO for next fiscal year security investments. Media call with PR team following a public data breach in the industry. Review and sign off on updated incident response plan.',
    resources: ['SANS Leadership courses (MGT512, MGT516)', 'CISO Lens community', 'FAIR Institute risk quantification training', 'Harvard Executive Education cybersecurity programs'],
  },
  {
    id: 'bug-bounty',
    title: 'Bug Bounty Hunter',
    subtitle: 'Independent Vulnerability Researcher',
    level: 'any',
    track: 'offensive',
    icon: '&#128184;',
    color: '#facc15',
    salary: '$0 – $50,000 (part-time)',
    salaryMid: '$50,000 – $500,000+ (full-time)',
    experience: 'Any level',
    desc: 'Independently find and responsibly disclose security vulnerabilities in exchange for monetary rewards on bug bounty platforms.',
    overview: 'Bug bounty hunters are independent security researchers who find vulnerabilities in company systems and report them through structured programs. Platforms like HackerOne and Bugcrowd connect researchers with companies. Income is entirely variable — based on skill, specialization, and the programs you target. Top researchers earn hundreds of thousands annually; beginners may earn little to nothing initially.',
    technicalSkills: [
      'Web application testing (Burp Suite Pro, OWASP methodology)',
      'API security testing',
      'Recon automation (Amass, subfinder, httpx, nuclei)',
      'Mobile application testing (iOS and Android)',
      'Logic flaw identification (not just technical bugs)',
      'Report writing — clear PoC with business impact',
      'Scripting for automation (Python, Bash)',
      'Specialization in one area (cloud, IoT, crypto, AI)',
    ],
    softSkills: [
      'Self-motivation and discipline — no manager, no deadlines',
      'Persistence through many "not a bug" responses',
      'Creativity in finding non-obvious attack chains',
      'Business understanding — high-impact bugs get paid more',
      'Professional communication with program security teams',
    ],
    certifications: [
      { name: 'OSCP / OSWE', desc: 'Strong pentest certs that demonstrate skill to programs and employers.', priority: 'recommended' },
      { name: 'BSCP (PortSwigger Burp Suite Certified)', desc: 'Practical web security cert. Directly relevant to bug bounty skills.', priority: 'recommended' },
    ],
    entryPath: 'Start on HackerOne or Bugcrowd with public programs that have broad scopes. Begin with recon — find as much surface area as possible. Focus on one vulnerability class to build expertise. Read disclosed reports from top researchers to learn methodology. Expect low/no earnings for the first 6–12 months.',
    careerPath: {
      from: ['Any technical background', 'Self-taught', 'Pentest experience'],
      to: ['Full-time Bug Bounty', 'Penetration Tester', 'Security Researcher at Vendor', 'Starting a Consultancy'],
    },
    dayInLife: 'Spend 2 hours on reconnaissance against a new target — map subdomains, enumerate endpoints, identify technologies. Find an interesting authentication flow and begin manual testing. Discover an IDOR vulnerability allowing access to other users\' data. Write a clear PoC report with step-by-step reproduction and business impact. Submit. Wait for triage.',
    resources: ['HackerOne Hacker101 (free)', 'PortSwigger Web Security Academy (free)', 'Bug bounty disclosed reports on HackerOne', 'Jason Haddix methodology talks'],
  },
];
