// ============================================================
//  RESOURCES DATA — Study Materials & Certifications
// ============================================================

const CERTIFICATIONS = [
  // ---- ENTRY LEVEL -----------------------------------------------------------
  {
    id: 'comptia-sec',
    name: 'CompTIA Security+',
    issuer: 'CompTIA',
    level: 'entry',
    track: 'general',
    cost: '~$392 exam',
    duration: '2–3 months study',
    renewal: 'Every 3 years (CEUs or re-exam)',
    icon: '&#128737;',
    color: '#58a6ff',
    summary: 'The most widely recognized entry-level security certification. Covers network security, threats, cryptography, risk management, and compliance. Required or preferred by many government and enterprise employers.',
    domains: [
      'Threats, Attacks & Vulnerabilities',
      'Architecture & Design',
      'Implementation',
      'Operations & Incident Response',
      'Governance, Risk & Compliance',
    ],
    prerequisites: 'None required. CompTIA Network+ or 2 years IT experience recommended.',
    whoShouldGet: 'Anyone starting a career in security — SOC analysts, sysadmins moving into security, military/veterans (DoD 8570 approved).',
    studyResources: ['Professor Messer (free YouTube/notes)', 'Jason Dion practice exams (Udemy)', 'CompTIA official study guide', 'TryHackMe CompTIA path'],
    passRate: '~83%',
    jobTitles: ['SOC Analyst', 'Security Analyst', 'IT Security Specialist', 'Systems Administrator'],
  },
  {
    id: 'google-cyber',
    name: 'Google Cybersecurity Certificate',
    issuer: 'Google / Coursera',
    level: 'entry',
    track: 'general',
    cost: '~$49/month (Coursera)',
    duration: '3–6 months',
    renewal: 'No renewal required',
    icon: '&#127758;',
    color: '#3fb950',
    summary: 'A beginner-friendly online certificate from Google covering security fundamentals, Linux, SQL, SIEM tools, and Python scripting. Best for complete career changers with no IT background.',
    domains: [
      'Security foundations',
      'Network security',
      'Linux & SQL basics',
      'Detection & response',
      'Python automation',
    ],
    prerequisites: 'None. No prior IT experience needed.',
    whoShouldGet: 'Career changers, recent graduates, and anyone wanting a low-cost introduction to security before pursuing Security+.',
    studyResources: ['Coursera platform (self-paced)', 'Google supplemental labs'],
    passRate: 'Self-paced — no pass/fail exam',
    jobTitles: ['Entry-level SOC Analyst', 'IT Support (security focus)', 'Junior Security Analyst'],
  },
  {
    id: 'comptia-network',
    name: 'CompTIA Network+',
    issuer: 'CompTIA',
    level: 'entry',
    track: 'general',
    cost: '~$338 exam',
    duration: '2–3 months study',
    renewal: 'Every 3 years (CEUs or re-exam)',
    icon: '&#128268;',
    color: '#fb923c',
    summary: 'Validates core networking skills — protocols, topologies, troubleshooting, and infrastructure. Not a security cert per se, but essential knowledge for any security role. Often taken before Security+.',
    domains: [
      'Networking fundamentals',
      'Network implementations',
      'Network operations',
      'Network security',
      'Network troubleshooting',
    ],
    prerequisites: 'CompTIA A+ or 9–12 months networking experience recommended.',
    whoShouldGet: 'Future SOC analysts, network security engineers, anyone without a networking background who needs the fundamentals.',
    studyResources: ['Professor Messer Network+ (free)', 'Mike Meyers Udemy course', 'ExamCompass free practice tests'],
    passRate: '~77%',
    jobTitles: ['Network Technician', 'Junior Network Engineer', 'IT Support Specialist'],
  },
  {
    id: 'cysa-plus',
    name: 'CompTIA CySA+',
    issuer: 'CompTIA',
    level: 'mid',
    track: 'defensive',
    cost: '~$392 exam',
    duration: '2–4 months study',
    renewal: 'Every 3 years (CEUs or re-exam)',
    icon: '&#128270;',
    color: '#58a6ff',
    summary: 'Analyst-focused cert covering threat intelligence, vulnerability management, behavioral analytics, and incident response. Bridges the gap between Security+ and advanced certs. DoD 8570 approved.',
    domains: [
      'Threat and vulnerability management',
      'Software and systems security',
      'Security operations and monitoring',
      'Incident response',
      'Compliance and assessment',
    ],
    prerequisites: 'Security+ or 4 years hands-on experience recommended.',
    whoShouldGet: 'Working SOC analysts moving to Tier 2/3, threat hunters, incident responders wanting vendor-neutral recognition.',
    studyResources: ['Jason Dion Udemy course', 'CompTIA CySA+ study guide', 'TryHackMe SOC Level 2 path'],
    passRate: '~73%',
    jobTitles: ['Tier 2 SOC Analyst', 'Threat Intelligence Analyst', 'Security Operations Specialist'],
  },

  // ---- MID LEVEL -------------------------------------------------------------
  {
    id: 'ejpt',
    name: 'eJPT (eLearnSecurity Junior Penetration Tester)',
    issuer: 'INE Security (eLearnSecurity)',
    level: 'entry',
    track: 'offensive',
    cost: '~$200 (includes training)',
    duration: '1–2 months',
    renewal: 'No renewal required',
    icon: '&#128295;',
    color: '#d29922',
    summary: 'Hands-on entry-level penetration testing cert with a fully practical exam. Tests real skills like network scanning, exploitation, and pivoting inside a live lab environment. Great first offensive cert.',
    domains: [
      'Network fundamentals',
      'Web application attacks',
      'Host & network penetration testing',
      'Exploitation basics',
    ],
    prerequisites: 'Basic networking and Linux knowledge helpful. Free INE Starter Pass covers prerequisites.',
    whoShouldGet: 'Anyone wanting to break into offensive security. Excellent first cert before OSCP.',
    studyResources: ['INE free Starter Pass (official prep)', 'TryHackMe Jr Penetration Tester path', 'HackTheBox Starting Point'],
    passRate: 'Not published — practical lab exam',
    jobTitles: ['Junior Penetration Tester', 'Security Analyst (offensive focus)', 'Bug Bounty Hunter'],
  },
  {
    id: 'btl1',
    name: 'BTL1 (Blue Team Labs Level 1)',
    issuer: 'Security Blue Team',
    level: 'entry',
    track: 'defensive',
    cost: '~$599 (includes 4-month access)',
    duration: '2–4 months',
    renewal: 'No renewal required',
    icon: '&#128274;',
    color: '#58a6ff',
    summary: 'Fully practical defensive security cert with a 24-hour hands-on exam. Covers SIEM, log analysis, phishing analysis, digital forensics, and incident response. Highly respected in SOC hiring.',
    domains: [
      'Phishing analysis',
      'Threat intelligence',
      'Digital forensics',
      'SIEM and log analysis',
      'Incident response',
    ],
    prerequisites: 'None, but Security+ knowledge level recommended.',
    whoShouldGet: 'SOC analysts wanting a practical cert that stands out over paper-based options.',
    studyResources: ['Security Blue Team official courseware (included)', 'Blue Team Labs Online (free labs)'],
    passRate: 'Not published — 24-hour practical exam',
    jobTitles: ['SOC Analyst', 'Incident Responder', 'Cyber Defence Analyst'],
  },
  {
    id: 'ceh',
    name: 'CEH (Certified Ethical Hacker)',
    issuer: 'EC-Council',
    level: 'mid',
    track: 'offensive',
    cost: '~$1,199 exam + training',
    duration: '2–4 months',
    renewal: 'Every 3 years (ECE credits)',
    icon: '&#128526;',
    color: '#d29922',
    summary: 'One of the most recognized offensive certifications, covering 20 hacking domains. More knowledge-based than hands-on compared to OSCP. DoD 8570 approved — valuable for government/federal roles.',
    domains: [
      'Footprinting & reconnaissance',
      'Scanning networks',
      'Enumeration & vulnerability analysis',
      'System hacking',
      'Malware threats',
      'Web application hacking',
      'Social engineering',
    ],
    prerequisites: '2 years IT security experience or official EC-Council training.',
    whoShouldGet: 'Pentesters targeting government/federal roles, security professionals needing DoD 8570 compliance.',
    studyResources: ['Matt Walker CEH study guide', 'EC-Council official courseware', 'Boson practice exams'],
    passRate: '~70%',
    jobTitles: ['Penetration Tester', 'Ethical Hacker', 'Security Consultant', 'Vulnerability Analyst'],
  },
  {
    id: 'oscp',
    name: 'OSCP (Offensive Security Certified Professional)',
    issuer: 'Offensive Security',
    level: 'mid',
    track: 'offensive',
    cost: '~$1,499 (90-day lab access + exam)',
    duration: '3–6 months preparation',
    renewal: 'No renewal required',
    icon: '&#9876;',
    color: '#f85149',
    summary: 'The gold standard penetration testing certification. Entirely hands-on — a 24-hour exam where you must compromise machines in a live network. Proves real-world exploitation skills. Highly sought after by employers.',
    domains: [
      'Active reconnaissance',
      'Vulnerability scanning',
      'Web application attacks',
      'Buffer overflows',
      'Active Directory attacks',
      'Privilege escalation',
      'Post-exploitation',
      'Pivoting & tunneling',
    ],
    prerequisites: 'Strong Linux, networking, and scripting skills. eJPT/PNPT recommended as stepping stones.',
    whoShouldGet: 'Anyone serious about penetration testing as a career. The cert most hiring managers actively look for.',
    studyResources: ['OffSec PEN-200 course (official — included)', 'TryHackMe / HackTheBox for prep', 'TCM Security PNPT as warm-up', 'IppSec YouTube for HTB walkthroughs'],
    passRate: '~15–20% on first attempt',
    jobTitles: ['Penetration Tester', 'Red Team Operator', 'Security Consultant', 'Vulnerability Researcher'],
  },
  {
    id: 'pnpt',
    name: 'PNPT (Practical Network Penetration Tester)',
    issuer: 'TCM Security',
    level: 'mid',
    track: 'offensive',
    cost: '~$399',
    duration: '2–4 months',
    renewal: 'No renewal required',
    icon: '&#128187;',
    color: '#d29922',
    summary: 'Fully practical penetration testing cert from TCM Security. Includes a 5-day exam where you compromise a network and write a professional report. Great OSCP alternative/stepping stone — highly respected and more affordable.',
    domains: [
      'External and internal network pentesting',
      'Active Directory attacks',
      'Web application testing',
      'Report writing',
    ],
    prerequisites: 'Basic networking and Linux. TCM Security courses included with purchase.',
    whoShouldGet: 'Aspiring pentesters who want OSCP-quality practical skills at a lower price point.',
    studyResources: ['TCM Security courses (included)', 'TryHackMe Jr Pentester path', 'HackTheBox Academy'],
    passRate: 'Not published — practical exam',
    jobTitles: ['Junior Penetration Tester', 'Red Team Analyst', 'Security Consultant'],
  },

  // ---- ADVANCED / SENIOR -----------------------------------------------------
  {
    id: 'cissp',
    name: 'CISSP (Certified Information Systems Security Professional)',
    issuer: 'ISC2',
    level: 'senior',
    track: 'general',
    cost: '~$699 exam',
    duration: '6–12 months study',
    renewal: 'Every 3 years (CPE credits)',
    icon: '&#127891;',
    color: '#a78bfa',
    summary: 'The premier managerial/architectural security certification. Covers 8 security domains at a conceptual level. Required for senior security roles, management, and government positions. Often called the "gold standard" for security professionals.',
    domains: [
      'Security & Risk Management',
      'Asset Security',
      'Security Architecture & Engineering',
      'Communication & Network Security',
      'Identity & Access Management',
      'Security Assessment & Testing',
      'Security Operations',
      'Software Development Security',
    ],
    prerequisites: '5 years paid work experience in 2+ CISSP domains. Associate CISSP available without experience.',
    whoShouldGet: 'Security managers, architects, directors, and senior engineers targeting leadership roles.',
    studyResources: ['Destination CISSP (free podcast)', 'Thor Teaches CISSP (Udemy)', 'ISC2 official study guide', 'Boson CISSP practice exams'],
    passRate: '~40–50%',
    jobTitles: ['Security Manager', 'Security Architect', 'CISO', 'Security Director', 'Senior Security Engineer'],
  },
  {
    id: 'gcia',
    name: 'GCIA (GIAC Certified Intrusion Analyst)',
    issuer: 'GIAC / SANS',
    level: 'senior',
    track: 'defensive',
    cost: '~$949 exam ($7,000+ with SANS training)',
    duration: '3–6 months',
    renewal: 'Every 4 years',
    icon: '&#128202;',
    color: '#3fb950',
    summary: 'Advanced defensive cert focused on network traffic analysis, intrusion detection, and packet analysis. Highly technical and hands-on. Part of the SANS/GIAC ecosystem — extremely well respected by blue teamers.',
    domains: [
      'TCP/IP and protocol analysis',
      'Network forensics',
      'Intrusion detection (Snort/Suricata)',
      'IDS/IPS tuning',
      'Application protocol analysis',
    ],
    prerequisites: 'Strong networking fundamentals. Security+ and CySA+ level knowledge recommended.',
    whoShouldGet: 'Network defenders, SOC Tier 2/3 analysts, threat hunters wanting deep packet analysis skills.',
    studyResources: ['SANS SEC503 (official — expensive)', 'Chris Sanders Applied Network Security Monitoring (book)', 'Wireshark documentation', 'VirusTotal and pcap practice files'],
    passRate: 'Not publicly reported',
    jobTitles: ['Network Security Analyst', 'Intrusion Analyst', 'Threat Hunter', 'SOC Lead'],
  },
  {
    id: 'gcih',
    name: 'GCIH (GIAC Certified Incident Handler)',
    issuer: 'GIAC / SANS',
    level: 'mid',
    track: 'defensive',
    cost: '~$949 exam ($7,000+ with SANS training)',
    duration: '3–6 months',
    renewal: 'Every 4 years',
    icon: '&#128680;',
    color: '#f85149',
    summary: 'Covers the incident handling process end-to-end — detection, containment, eradication, and recovery. Includes offensive knowledge of common attacks so defenders understand what they are responding to.',
    domains: [
      'Incident handling process',
      'Computer crime investigation',
      'Hacker exploits and attack techniques',
      'Worms and botnets',
      'Penetration testing concepts',
    ],
    prerequisites: 'Security+ level knowledge. Some offensive security understanding helpful.',
    whoShouldGet: 'Incident responders, SOC managers, forensics analysts, blue teamers wanting offensive context.',
    studyResources: ['SANS SEC504 (official)', 'SANS reading room whitepapers (free)', 'Blue Team Labs Online'],
    passRate: 'Not publicly reported',
    jobTitles: ['Incident Responder', 'SOC Analyst Tier 2', 'Forensics Analyst', 'Threat Hunter'],
  },
  {
    id: 'cism',
    name: 'CISM (Certified Information Security Manager)',
    issuer: 'ISACA',
    level: 'senior',
    track: 'governance',
    cost: '~$760 exam (member) / $895 (non-member)',
    duration: '4–6 months',
    renewal: 'Every 3 years (CPE credits)',
    icon: '&#128203;',
    color: '#a78bfa',
    summary: 'Management-focused security cert for those who design and manage enterprise security programs. Covers governance, risk management, incident management, and program development. Favored by CISOs and security directors.',
    domains: [
      'Information Security Governance',
      'Information Risk Management',
      'Information Security Program Development',
      'Information Security Incident Management',
    ],
    prerequisites: '5 years information security management experience.',
    whoShouldGet: 'Security managers, GRC professionals, and CISO-track candidates.',
    studyResources: ['ISACA official review manual', 'Hemang Doshi Udemy CISM course', 'CISM QAE practice questions'],
    passRate: '~50%',
    jobTitles: ['Security Manager', 'GRC Manager', 'Information Security Officer', 'CISO'],
  },
  {
    id: 'aws-security',
    name: 'AWS Certified Security — Specialty',
    issuer: 'Amazon Web Services',
    level: 'senior',
    track: 'engineering',
    cost: '~$300 exam',
    duration: '3–6 months',
    renewal: 'Every 3 years',
    icon: '&#9729;',
    color: '#fb923c',
    summary: 'Validates advanced AWS security skills: IAM, logging, encryption, network controls, and incident response in AWS. Essential for cloud security engineers working in AWS environments.',
    domains: [
      'Threat detection and incident response',
      'Logging and monitoring',
      'Infrastructure security',
      'Identity and access management',
      'Data protection',
    ],
    prerequisites: 'AWS Solutions Architect Associate recommended. 2+ years hands-on AWS security experience.',
    whoShouldGet: 'Cloud security engineers, DevSecOps engineers, and architects working primarily in AWS.',
    studyResources: ['Adrian Cantrill AWS courses', 'AWS Security workshop (free)', 'Stephane Maarek Udemy course', 'AWS whitepapers (free)'],
    passRate: '~65%',
    jobTitles: ['Cloud Security Engineer', 'AWS Security Architect', 'DevSecOps Engineer'],
  },
];

// ---- STUDY MATERIALS --------------------------------------------------------
const STUDY_MATERIALS = [
  {
    id: 'free-platforms',
    category: 'Free Learning Platforms',
    icon: '&#127891;',
    color: '#3fb950',
    items: [
      {
        name: 'TryHackMe',
        url: 'tryhackme.com',
        desc: 'Browser-based learning platform with guided rooms and structured learning paths. Best starting point for beginners. Free tier available, premium ~$14/month.',
        tags: ['Beginner-friendly', 'Guided paths', 'SOC', 'Pentesting', 'Browser-based'],
        recommended: true,
      },
      {
        name: 'HackTheBox Academy',
        url: 'academy.hackthebox.com',
        desc: 'Structured learning paths from beginner to advanced. More technical than TryHackMe. Free tier available, annual subscriptions for full access.',
        tags: ['Beginner to Advanced', 'Offensive', 'Defensive', 'Structured modules'],
        recommended: true,
      },
      {
        name: 'PortSwigger Web Security Academy',
        url: 'portswigger.net/web-security',
        desc: '100% free, world-class web application security training from the makers of Burp Suite. Covers every major web vulnerability with interactive labs.',
        tags: ['Web AppSec', 'Free', 'Interactive labs', 'Bug bounty prep'],
        recommended: true,
      },
      {
        name: 'Blue Team Labs Online',
        url: 'blueteamlabs.online',
        desc: 'Free defensive security challenges covering SIEM, log analysis, network forensics, and incident response. Great for SOC skill building.',
        tags: ['Defensive', 'SOC', 'SIEM', 'Free labs'],
        recommended: false,
      },
      {
        name: 'LetsDefend',
        url: 'letsdefend.io',
        desc: 'SOC analyst simulation platform. Investigate alerts, analyze malware, and work real-world defensive scenarios. Free and paid tiers.',
        tags: ['SOC simulation', 'Malware analysis', 'Alert triage', 'Defensive'],
        recommended: false,
      },
      {
        name: 'Cybrary',
        url: 'cybrary.it',
        desc: 'Large library of security courses, career paths, and virtual labs. Free tier available with courses from industry professionals.',
        tags: ['Courses', 'Career paths', 'Free tier', 'Certifications prep'],
        recommended: false,
      },
    ],
  },
  {
    id: 'youtube',
    category: 'YouTube Channels',
    icon: '&#127910;',
    color: '#f85149',
    items: [
      {
        name: 'Professor Messer',
        url: 'professormesser.com',
        desc: 'Free, comprehensive CompTIA certification study videos (Security+, Network+, A+). The go-to free resource for CompTIA exam prep.',
        tags: ['CompTIA', 'Security+', 'Network+', 'Free', 'Certification prep'],
        recommended: true,
      },
      {
        name: 'IppSec',
        url: 'youtube.com/@ippsec',
        desc: 'In-depth walkthroughs of retired HackTheBox machines. Essential for understanding penetration testing methodology and thinking like an attacker.',
        tags: ['HTB walkthroughs', 'Offensive', 'Intermediate-Advanced', 'Methodology'],
        recommended: true,
      },
      {
        name: 'John Hammond',
        url: 'youtube.com/@_JohnHammond',
        desc: 'CTF walkthroughs, malware analysis, reverse engineering, and security tutorials. Excellent mix of offensive and defensive content.',
        tags: ['CTF', 'Malware', 'Reversing', 'Beginner to Advanced'],
        recommended: true,
      },
      {
        name: 'TCM Security',
        url: 'youtube.com/@TCMSecurityAcademy',
        desc: 'Practical ethical hacking tutorials from Heath Adams. Free course content covering Active Directory attacks, OSINT, and web hacking.',
        tags: ['Ethical hacking', 'Active Directory', 'OSINT', 'Free courses'],
        recommended: true,
      },
      {
        name: 'David Bombal',
        url: 'youtube.com/@davidbombal',
        desc: 'Networking and security content including Python scripting, Kali Linux, and network configuration tutorials.',
        tags: ['Networking', 'Python', 'Kali Linux', 'Beginner-friendly'],
        recommended: false,
      },
      {
        name: 'NetworkChuck',
        url: 'youtube.com/@NetworkChuck',
        desc: 'Entertaining networking and security tutorials covering Linux, Docker, VPNs, and hacking basics. Very beginner-friendly.',
        tags: ['Networking', 'Linux', 'Beginner-friendly', 'Entertaining'],
        recommended: false,
      },
    ],
  },
  {
    id: 'ctf',
    category: 'CTF & Practice Labs',
    icon: '&#127984;',
    color: '#d29922',
    items: [
      {
        name: 'HackTheBox',
        url: 'hackthebox.com',
        desc: 'The premier platform for practicing penetration testing skills against realistic machines. Active machines require finding exploits yourself — very hands-on.',
        tags: ['Intermediate-Advanced', 'Offensive', 'Competitive', 'Realistic'],
        recommended: true,
      },
      {
        name: 'PicoCTF',
        url: 'picoctf.org',
        desc: 'Free CTF competition platform from Carnegie Mellon. Great for absolute beginners learning web exploitation, cryptography, and reverse engineering basics.',
        tags: ['Beginner', 'CTF', 'Free', 'Web', 'Crypto', 'Reversing'],
        recommended: true,
      },
      {
        name: 'CTFtime',
        url: 'ctftime.org',
        desc: 'Calendar and archive of global CTF competitions. Find upcoming events to compete in and study writeups from past competitions.',
        tags: ['CTF calendar', 'Competitions', 'Writeups', 'All levels'],
        recommended: false,
      },
      {
        name: 'VulnHub',
        url: 'vulnhub.com',
        desc: 'Free download of intentionally vulnerable VMs to practice penetration testing offline. Hundreds of machines at all difficulty levels.',
        tags: ['Free', 'Offline VMs', 'Pentesting', 'Beginner to Advanced'],
        recommended: false,
      },
      {
        name: 'DVWA (Damn Vulnerable Web App)',
        url: 'github.com/digininja/DVWA',
        desc: 'A PHP/MySQL web application intentionally vulnerable to common web attacks. Self-hosted, free, and used to practice SQLi, XSS, CSRF, and more.',
        tags: ['Web AppSec', 'Self-hosted', 'Free', 'SQLi', 'XSS'],
        recommended: false,
      },
      {
        name: 'Hack The Box Sherlocks',
        url: 'hackthebox.com/sherlocks',
        desc: 'Blue team forensics and incident response challenges on HTB. Investigate realistic attack scenarios using logs, artifacts, and memory dumps.',
        tags: ['Defensive', 'Forensics', 'Incident response', 'Blue team'],
        recommended: false,
      },
    ],
  },
  {
    id: 'books',
    category: 'Books & Reading',
    icon: '&#128218;',
    color: '#a78bfa',
    items: [
      {
        name: 'The Web Application Hacker\'s Handbook (2nd Ed.)',
        url: null,
        desc: 'Comprehensive guide to finding and exploiting web application vulnerabilities. Older but foundational — covers methodology that still applies today.',
        tags: ['Web AppSec', 'Offensive', 'Classic', 'Intermediate'],
        recommended: true,
      },
      {
        name: 'Penetration Testing by Georgia Weidman',
        url: null,
        desc: 'Practical intro to penetration testing covering lab setup, exploitation, post-exploitation, and web hacking. Great entry-level offensive book.',
        tags: ['Pentesting', 'Entry-level', 'Lab setup', 'Practical'],
        recommended: true,
      },
      {
        name: 'The Practice of Network Security Monitoring',
        url: null,
        desc: 'By Richard Bejtlich. Teaches NSM methodology, Zeek/Bro, and defensive analysis. Essential for blue teamers and SOC analysts.',
        tags: ['Defensive', 'NSM', 'SOC', 'Blue team', 'Network analysis'],
        recommended: true,
      },
      {
        name: 'Blue Team Handbook: Incident Response Edition',
        url: null,
        desc: 'Practical field reference for incident responders covering tools, processes, and checklists. Compact and useful on the job.',
        tags: ['Incident response', 'Defensive', 'Reference', 'Practical'],
        recommended: false,
      },
      {
        name: 'Hacking: The Art of Exploitation (2nd Ed.)',
        url: null,
        desc: 'By Jon Erickson. Deep dive into low-level exploitation, buffer overflows, shellcode, and C programming for security. Technical but rewarding.',
        tags: ['Exploitation', 'Low-level', 'Advanced', 'C programming'],
        recommended: false,
      },
      {
        name: 'NIST Cybersecurity Framework (free PDF)',
        url: 'nist.gov/cyberframework',
        desc: 'The free framework document from NIST covering Identify, Protect, Detect, Respond, Recover. Essential reading for GRC and security management roles.',
        tags: ['GRC', 'Framework', 'Free', 'Governance', 'Management'],
        recommended: false,
      },
    ],
  },
  {
    id: 'paid-courses',
    category: 'Paid Courses & Bootcamps',
    icon: '&#127979;',
    color: '#58a6ff',
    items: [
      {
        name: 'TCM Security Practical Courses',
        url: 'academy.tcm-sec.com',
        desc: 'High-quality, affordable penetration testing and defensive courses. Practical Ethical Hacking, Active Directory, OSINT, and more — $30–$60 per course.',
        tags: ['Affordable', 'Practical', 'Pentesting', 'Active Directory', 'OSINT'],
        recommended: true,
      },
      {
        name: 'SANS Institute',
        url: 'sans.org',
        desc: 'Industry-leading cybersecurity training. Expensive ($5,000–$8,000 per course) but world-class quality. GIAC certs bundled. Look for work-funded options.',
        tags: ['Premium', 'GIAC certs', 'Advanced', 'Industry-leading', 'Work-funded'],
        recommended: false,
      },
      {
        name: 'Offensive Security (OffSec)',
        url: 'offsec.com',
        desc: 'Creators of Kali Linux and OSCP. Subscription-based access to PEN-200, WEB-200, and more. Essential if pursuing OSCP or OSWP certifications.',
        tags: ['OSCP prep', 'Offensive', 'Professional', 'Lab access'],
        recommended: true,
      },
      {
        name: 'INE Security',
        url: 'ine.com',
        desc: 'Platform offering eJPT, eCPPT, and eWPT certifications with included training. Free Starter Pass covers networking and security fundamentals.',
        tags: ['eJPT', 'eCPPT', 'Practical certs', 'Free starter tier'],
        recommended: false,
      },
      {
        name: 'Jason Dion (Udemy)',
        url: 'udemy.com',
        desc: 'Affordable, highly-rated CompTIA and security exam prep courses on Udemy. Security+, CySA+, PenTest+ practice exams are among the best available.',
        tags: ['CompTIA prep', 'Practice exams', 'Affordable', 'Security+', 'CySA+'],
        recommended: true,
      },
    ],
  },
  {
    id: 'communities',
    category: 'Communities & News',
    icon: '&#128101;',
    color: '#3fb950',
    items: [
      {
        name: 'r/cybersecurity & r/netsec',
        url: 'reddit.com/r/cybersecurity',
        desc: 'Active Reddit communities for career advice, news, and tool discussions. r/netsec is more technical; r/cybersecurity is broader and career-focused.',
        tags: ['Community', 'Career advice', 'News', 'Discussion'],
        recommended: true,
      },
      {
        name: 'Krebs on Security',
        url: 'krebsonsecurity.com',
        desc: 'In-depth investigative security journalism by Brian Krebs. Covers breaches, cybercrime, and industry trends. Essential news reading.',
        tags: ['News', 'Journalism', 'Breaches', 'Industry trends'],
        recommended: true,
      },
      {
        name: 'SANS Internet Storm Center',
        url: 'isc.sans.edu',
        desc: 'Daily threat intelligence and diaries from SANS handlers. Free, technical, and up-to-date on current threats and vulnerabilities.',
        tags: ['Threat intel', 'Free', 'Daily updates', 'Technical'],
        recommended: false,
      },
      {
        name: 'Hacker News (security tag)',
        url: 'news.ycombinator.com',
        desc: 'Tech community news aggregator. Filter by "security" or "netsec" for relevant discussions on vulnerabilities, tools, and research.',
        tags: ['News aggregator', 'Tech community', 'Research', 'Vulnerabilities'],
        recommended: false,
      },
      {
        name: 'MITRE ATT&CK Framework',
        url: 'attack.mitre.org',
        desc: 'Free knowledge base of adversary tactics and techniques based on real-world observations. Essential reference for threat hunters, blue teamers, and red teamers.',
        tags: ['Threat intel', 'Framework', 'Free', 'ATT&CK', 'Blue and red team'],
        recommended: true,
      },
    ],
  },
];
